package io.github.moosyu.registers;

import io.github.moosyu.attributes.ModAttributes;
import io.github.moosyu.items.*;
import io.github.moosyu.rarities.RarityTypes;
import net.minecraft.core.Holder;
import net.minecraft.core.component.DataComponents;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.EquipmentSlotGroup;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.item.*;
import net.minecraft.world.item.component.ItemAttributeModifiers;
import net.minecraft.world.item.equipment.ArmorType;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

import static io.github.moosyu.Unshattered.MODID;
import static io.github.moosyu.registers.ArmorMaterialRegister.LEAFLET_ARMOR_MATERIAL;
import static io.github.moosyu.registers.BlocksRegistry.EXAMPLE_BLOCK;
import static io.github.moosyu.registers.BlocksRegistry.FIG_LOG_BLOCK;

public class ItemsRegistry {
    // Create a Deferred Register to hold Items which will all be registered under the "unshattered" namespace
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(MODID);
    // Creates a new BlockItem with the id "unshattered:example_block", combining the namespace and path
    public static final DeferredItem<BlockItem> EXAMPLE_BLOCK_ITEM = ITEMS.registerSimpleBlockItem("example_block", EXAMPLE_BLOCK);

    public static final DeferredItem<UnshatteredAxeWeapon> MERCENARY_AXE = ITEMS.register("mercenary_axe", () -> new UnshatteredAxeWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.RARE).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "mercenary_axe_damage"), 70, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).add(ModAttributes.STRENGTH.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "mercenary_axe_strength"), 20, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredSwordWeapon> WOODEN_SWORD = ITEMS.register("wooden_sword", () -> new UnshatteredSwordWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "wooden_sword_damage"), 20, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeWeapon> STONE_SWORD = ITEMS.register("stone_sword", () -> new UnshatteredAxeWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "stone_sword_damage"), 25, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredSwordWeapon> IRON_SWORD = ITEMS.register("iron_sword", () -> new UnshatteredSwordWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "iron_sword_damage"), 30, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredSwordWeapon> GOLDEN_SWORD = ITEMS.register("golden_sword", () -> new UnshatteredSwordWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "golden_sword_damage"), 20, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredSwordWeapon> DIAMOND_SWORD = ITEMS.register("diamond_sword", () -> new UnshatteredSwordWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.UNCOMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "diamond_sword_damage"), 35, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeWeapon> WOODEN_AXE = ITEMS.register("wooden_axe", () -> new UnshatteredAxeWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "wooden_axe_damage"), 10, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeWeapon> STONE_AXE = ITEMS.register("stone_axe", () -> new UnshatteredAxeWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "stone_axe_damage"), 15, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeWeapon> GOLDEN_AXE = ITEMS.register("golden_axe", () -> new UnshatteredAxeWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "golden_axe_damage"), 20, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeWeapon> IRON_AXE = ITEMS.register("iron_axe", () -> new UnshatteredAxeWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "iron_axe_damage"), 25, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeWeapon> DIAMOND_AXE = ITEMS.register("diamond_axe", () -> new UnshatteredAxeWeapon(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.UNCOMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.DAMAGE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "diamond_axe_damage"), 30, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    // todo: make it so the foraging fortune only applies in certain areas (the park, not the galatea)
    public static final DeferredItem<UnshatteredAxeTool> TREECAPITATOR = ITEMS.register("treecapitator", () -> new UnshatteredAxeTool(Tiers.GOLD, new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.EPIC).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.AXE).attributes(ItemAttributeModifiers.builder().add(ModAttributes.SWEEP.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "treecapitator_sweep"), 25, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "treecapitator_foraging_fortune"), 100, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    // todo: make it so the foraging fortune only applies in certain areas (the park, not the galatea)
    public static final DeferredItem<UnshatteredAxeTool> SPRUCE_AXE = ITEMS.register("spruce_axe", () -> new UnshatteredAxeTool(Tiers.WOOD, new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.UNCOMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.SWEEP.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "spruce_axe_sweep"), 4, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "spruce_axe_foraging_fortune"), 50, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeTool> SERIOUSLY_DAMAGED_AXE = ITEMS.register("seriously_damaged_axe", () -> new UnshatteredAxeTool(Tiers.WOOD, new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.UNCOMMON).attributes(ItemAttributeModifiers.builder().add(ModAttributes.SWEEP.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "seriously_damaged_axe_sweep"), 7, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "seriously_damaged_axe_foraging_fortune"), 5, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeTool> DECENT_AXE = ITEMS.register("decent_axe", () -> new UnshatteredAxeTool(Tiers.WOOD, new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.RARE).attributes(ItemAttributeModifiers.builder().add(ModAttributes.SWEEP.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "decent_axe_sweep"), 24, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "decent_axe_foraging_fortune"), 5, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeTool> FIG_HEW = ITEMS.register("fig_hew", () -> new UnshatteredAxeTool(Tiers.WOOD, new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.RARE).attributes(ItemAttributeModifiers.builder().add(ModAttributes.SWEEP.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "fig_hew_sweep"), 7, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "fig_hew_foraging_fortune"), 20, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<UnshatteredAxeTool> FIGSTONE_SPLITTER = ITEMS.register("figstone_splitter", () -> new UnshatteredAxeTool(Tiers.STONE, new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.EPIC).attributes(ItemAttributeModifiers.builder().add(ModAttributes.SWEEP.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "figstone_splitter_sweep"), 24, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "figstone_splitter_foraging_fortune"), 35, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.MAINHAND).build())));
    public static final DeferredItem<Item> LEAFLET_HELMET = ITEMS.registerItem("leaflet_helmet", props -> new Item(props.humanoidArmor(LEAFLET_ARMOR_MATERIAL, ArmorType.HELMET).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.HELMET).attributes(ItemAttributeModifiers.builder().add(ModAttributes.HEALTH.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_helmet_health"), 70, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.HEAD).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_helmet_foraging_fortune"), 3, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.HEAD).build())));
    public static final DeferredItem<UnshatteredItem> LEAFLET_CHESTPLATE = ITEMS.registerItem("leaflet_chestplate", props -> new UnshatteredItem(LEAFLET_ARMOR_MATERIAL, ArmorType.CHESTPLATE, new Item.Properties().component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.CHESTPLATE).attributes(ItemAttributeModifiers.builder().add(ModAttributes.HEALTH.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_chestplate_health"), 80, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.CHEST).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_chestplate_foraging_fortune"), 3, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.CHEST).build()), "Chestplate"));
    public static final DeferredItem<UnshatteredItem> LEAFLET_LEGGINGS = ITEMS.registerItem("leaflet_leggings", props -> new UnshatteredItem(LEAFLET_ARMOR_MATERIAL, ArmorType.LEGGINGS, new Item.Properties().component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.LEGGINGS).attributes(ItemAttributeModifiers.builder().add(ModAttributes.HEALTH.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_leggings_health"), 20, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.LEGS).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_leggings_foraging_fortune"), 3, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.LEGS).build()), "Leggings"));
    public static final DeferredItem<UnshatteredItem> LEAFLET_BOOTS = ITEMS.registerItem("leaflet_boots", props -> new UnshatteredItem(LEAFLET_ARMOR_MATERIAL, ArmorType.BOOTS, new Item.Properties().component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.BOOTS).attributes(ItemAttributeModifiers.builder().add(ModAttributes.HEALTH.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_boots_health"), 25, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.FEET).add(ModAttributes.FORAGING_FORTUNE.holder, new AttributeModifier(Identifier.fromNamespaceAndPath(MODID, "leaflet_boots_foraging_fortune"), 3, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.FEET).build()), "Boots"));
    public static final DeferredItem<UnshatteredEnchantedItem> BAT_THE_FISH = ITEMS.register("bat_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.bat_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> CENTURY_THE_FISH = ITEMS.register("century_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.century_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> CHILL_THE_FISH = ITEMS.register("chill_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.chill_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> CLUNK_THE_FISH = ITEMS.register("clunk_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.clunk_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> DIAMOND_THE_FISH = ITEMS.register("diamond_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.diamond_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> DUST_THE_FISH = ITEMS.register("dust_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.dust_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> EGG_THE_FISH = ITEMS.register("egg_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "This delicate, painted fish was found in the depths of the island during the Easter season.")));
    public static final DeferredItem<UnshatteredEnchantedItem> EON_THE_FISH = ITEMS.register("eon_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.eon_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> FLAKE_THE_FISH = ITEMS.register("flake_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.flake_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> EXPERIMENT_THE_FISH = ITEMS.register("experiment_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.experiment_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> FOSSIL_THE_FISH = ITEMS.register("fossil_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.fossil_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> GABAGOOL_THE_FISH = ITEMS.register("gabagool_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.gabagool_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> GIFT_THE_FISH = ITEMS.register("gift_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.gift_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> HERRING_THE_FISH = ITEMS.register("herring_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.herring_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> NOPE_THE_FISH = ITEMS.register("nope_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.nope_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> OOPS_THE_FISH = ITEMS.register("oops_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.oops_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> PARTY_THE_FISH = ITEMS.register("party_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.party_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> ROCK_THE_FISH = ITEMS.register("rock_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.rock_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> SHRIMP_THE_FISH = ITEMS.register("shrimp_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.shrimp_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> SKELETON_THE_FISH = ITEMS.register("skeleton_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.skeleton_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> SPOOK_THE_FISH = ITEMS.register("spook_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.spook_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> STEW_THE_FISH = ITEMS.register("stew_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.stew_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> SWAMP_THE_FISH = ITEMS.register("swamp_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.swamp_the_fish")));
    public static final DeferredItem<UnshatteredEnchantedItem> ZOOP_THE_FISH = ITEMS.register("zoop_the_fish", () -> new UnshatteredEnchantedItem(new Item.Properties().stacksTo(1).component(DataComponentRegistry.RARITY.get(), RarityTypes.SPECIAL).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.FISH).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.zoop_the_fish")));
    public static final DeferredItem<BlockItem> FIG_LOG = ITEMS.register("fig_log", () -> new BlockItem(FIG_LOG_BLOCK.get(), new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.COMMON).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.LOG).component(DataComponentRegistry.DESCRIPTION_KEY.get(), "item.description.unshattered.fig_log")));
    public static final DeferredItem<UnshatteredEnchantedItem> ENCHANTED_FIG_LOG = ITEMS.register("enchanted_fig_log", () -> new UnshatteredEnchantedItem(new Item.Properties().component(DataComponentRegistry.RARITY.get(), RarityTypes.RARE).component(DataComponentRegistry.ITEM_TYPE.get(), ItemTypes.LOG)));
}
